version: '3.8'

services:
  ollama:
    container_name: ollama
    image: ollama/ollama    
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_ORIGINS=*
    volumes:
      - /DATA/AppData/ollama:/root/.ollama
    restart: unless-stopped    

volumes:
  ollama:
